// =============================================================================
// tcGlobal.cpp - TrussC Global Functions Implementation
//
// Two kinds of definitions live here:
//
//   1. Large lifecycle / frame-management functions moved out of TrussC.h
//      to keep header compile times down (setup, cleanup, present, clear,
//      swapchain pass helpers, ...).
//
//   2. Singletons and accessors that MUST be non-inline so Host (EXE) and
//      Guest (DLL) share a single instance during hot reload on Windows.
//      `inline` functions with static locals create per-module instances
//      under MSVC's per-DLL symbol namespace — splitting events(),
//      getDefaultContext(), timers, the logger, etc. between modules
//      causes silent breakage (drawRectRounded white, tweens frozen, no
//      logs in guest, ...). Moving the definition into this .cpp keeps
//      one canonical instance shared via the host's exported symbols.
//
// When adding a new global singleton accessor, prefer defining it here
// (or in a sibling .cpp) rather than inline in a header.
// =============================================================================

#include <TrussC.h>

// Generated by sokol-shdc from core/shaders/sglPremult.glsl. Included here (one
// TU) rather than in the widely-included tcRenderTarget.h to avoid pulling the
// generated desc into every translation unit. The shader handle is exposed via
// internal::sglPremultShader().
#include "tc/gpu/shaders/sglPremult.glsl.h"

namespace trussc {

// ---------------------------------------------------------------------------
// Initialization (setup)
// ---------------------------------------------------------------------------
void setup() {
    // Initialize sokol_gfx (with memory tracking allocator)
    sg_desc sgdesc = {};
    sgdesc.environment = sglue_environment();
    sgdesc.logger.func = slog_func;
    sgdesc.pipeline_pool_size = 256;  // default 64 is too small when FBOs are used
    sgdesc.buffer_pool_size = 10000;  // default 128 too small with many meshes (only CPU slot table, not GPU memory)
    sgdesc.image_pool_size = 10000;
    sgdesc.view_pool_size = 10000;
    sgdesc.sampler_pool_size = 10000;
    // Per-frame uniform ring buffer (Metal/WebGPU/Vulkan; GL/D3D11 ignore it).
    // On Metal the ring auto-grows on overflow (x2 per step, with a warning log
    // — TrussC patch in sokol_gfx.h), so start small (1MB ≈ 2k draw calls per
    // frame, each apply 256-byte aligned) and let heavy scenes grow to size;
    // WindowSettings::reserveUniformBuffer just skips the one-time grow hitch.
    // WebGPU/Vulkan do NOT auto-grow: keep the 4MB sokol default there — past
    // the cap, RELEASE builds silently write out of bounds (garbage uniforms
    // render as flipped or fully black frames), so high-draw-count apps must
    // reserve enough up front. The backend allocates it x2 in-flight frames.
    if (internal::gpuUniformBufferReserve > 0) {
        sgdesc.uniform_buffer_size = internal::gpuUniformBufferReserve;
    }
    #if defined(SOKOL_METAL)
    else {
        sgdesc.uniform_buffer_size = 1024 * 1024;
    }
    #endif
    sgdesc.allocator.alloc_fn = smemtrack_alloc;
    sgdesc.allocator.free_fn = smemtrack_free;
    sg_setup(&sgdesc);

    // Initialize sokol_gl (with memory tracking allocator)
    sgl_desc_t sgldesc = {};
    sgldesc.logger.func = slog_func;
    sgldesc.pipeline_pool_size = 256;
    // sokol_gl's default of 4 contexts runs out fast: the swapchain takes one,
    // every secondary window takes one more, and Fbo::ensureShared() takes one
    // per (sample count, color format) combination. An app with a second window
    // and a couple of float FBO formats is already past four, and the overflow
    // is a per-frame SGL_LOGITEM_CONTEXT_POOL_EXHAUSTED with nothing drawn.
    sgldesc.context_pool_size = 64;
    sgldesc.max_vertices = internal::sglMaxVertices;
    sgldesc.max_commands = internal::sglMaxCommands;
    sgldesc.allocator.alloc_fn = smemtrack_alloc;
    sgldesc.allocator.free_fn = smemtrack_free;
    sgl_setup(&sgldesc);

    // RenderTarget: the swapchain target uses the default sgl context (carries the
    // swapchain color/depth format + sample count). Pipelines build lazily on first use.
    internal::currentWindowContext().swapchainTarget.context = sgl_default_context();
    internal::currentWindowContext().swapchainTarget.isFbo = false;

    // Initialize bitmap font sampler + pipeline. The atlas TEXTURE itself is
    // allocated lazily on first drawBitmapString call (see ensureFontAtlas in
    // TrussC.h) and grown tier-by-tier as new codepoint ranges are used.
    // Headless apps that never call drawBitmapString pay 0 KB for the atlas.
    if (!internal::fontInitialized) {
        // Sampler (nearest neighbor, pixel perfect)
        sg_sampler_desc smp_desc = {};
        smp_desc.min_filter = SG_FILTER_NEAREST;
        smp_desc.mag_filter = SG_FILTER_NEAREST;
        smp_desc.wrap_u = SG_WRAP_CLAMP_TO_EDGE;
        smp_desc.wrap_v = SG_WRAP_CLAMP_TO_EDGE;
        internal::fontSampler = sg_make_sampler(&smp_desc);

        internal::fontInitialized = true;
    }

    // The 3D / blend-mode / premultiplied / clear pipelines are no longer created
    // here: they are built lazily (and pre-warmed below) by the swapchain
    // RenderTarget, and per-format by each FBO's RenderTarget. See tcRenderTarget.h.

    // Pre-warm the swapchain RenderTarget pipeline cache so active2D/Premult/Clear/3D
    // never create an sgl pipeline mid-frame (lazy creation inside setupScreenFov
    // corrupted the frame; pre-creating here also avoids first-frame hitches).
    internal::active2D(BlendMode::Alpha);
    internal::active2D(BlendMode::Add);
    internal::active2D(BlendMode::Multiply);
    internal::active2D(BlendMode::Screen);
    internal::active2D(BlendMode::Subtract);
    internal::active2D(BlendMode::Disabled);
    internal::activePremult();
    internal::activeClear();
    internal::active3D();
}

// ---------------------------------------------------------------------------
// Cleanup (shutdown)
// ---------------------------------------------------------------------------
void cleanup() {
    // The 2D blend / 3D / premultiplied / clear sgl pipelines now live in the
    // swapchain and per-FBO RenderTarget caches; sgl_shutdown() below frees them
    // all (it destroys every pipeline in every sgl context), so there is nothing
    // to release individually here.

    // Release font resources
    if (internal::fontInitialized) {
        sg_destroy_sampler(internal::fontSampler);
        if (internal::fontAtlasInitialized) {
            sg_destroy_view(internal::fontView);
            sg_destroy_image(internal::fontTexture);
            internal::fontAtlasInitialized = false;
            internal::fontAtlasRows = 0;
        }
        internal::fontInitialized = false;
    }
    sgl_shutdown();
    sg_shutdown();
}

// ---------------------------------------------------------------------------
// Resize sokol_gl buffers (called when vertex/command overflow detected)
// Destroys and recreates sgl only — sg resources (textures, etc.) survive.
// ---------------------------------------------------------------------------
namespace internal {

// Premultiplied-alpha sgl shader (core/shaders/sglPremult.glsl), bound by the
// Screen/Multiply pipelines so their blend equations respect source alpha. Same
// ABI as sgl's built-in shader, so it drops into an sgl pipeline via
// sg_pipeline_desc.shader. Created once on first use (after sokol is up) and
// LEAKED on purpose: a static sg_shader destroyed at __cxa_finalize would call
// sg_destroy after sokol shutdown and crash. It is an sg (not sgl) resource, so
// it survives sgl_shutdown()/resizeSgl() like the font texture. Returns {0} if
// sokol isn't ready yet (caller then falls back to sgl's straight shader).
sg_shader sglPremultShader() {
    static sg_shader shd = {};
    if (shd.id == SG_INVALID_ID && sg_isvalid()) {
        shd = sg_make_shader(tc_sgl_premult_shader_desc(sg_query_backend()));
    }
    return shd;
}

void resizeSgl(int newMaxVertices, int newMaxCommands) {
    logNotice("sokol_gl") << "Resizing: vertices " << sglMaxVertices
        << " -> " << newMaxVertices << ", commands " << sglMaxCommands
        << " -> " << newMaxCommands;

    // 1. Shutdown and re-init sokol_gl with larger buffers. sgl_shutdown()
    //    destroys every pipeline in every sgl context (including the swapchain &
    //    FBO RenderTarget caches), so there is nothing to destroy by hand first.
    //    Font texture/sampler/view are sg resources — they survive sgl_shutdown.
    sgl_shutdown();

    sglMaxVertices = newMaxVertices;
    sglMaxCommands = newMaxCommands;

    sgl_desc_t sgldesc = {};
    sgldesc.logger.func = slog_func;
    sgldesc.pipeline_pool_size = 256;
    sgldesc.context_pool_size = 64;   // same reason as in the setup path above
    sgldesc.max_vertices = newMaxVertices;
    sgldesc.max_commands = newMaxCommands;
    sgldesc.allocator.alloc_fn = smemtrack_alloc;
    sgldesc.allocator.free_fn = smemtrack_free;
    sgl_setup(&sgldesc);

    // 2. The swapchain RenderTarget's cached pipelines are now stale (their context
    //    was torn down). Drop them and re-warm — the next frame's setupScreenFov
    //    runs every frame and would otherwise create a pipeline mid-frame, which
    //    corrupts the frame (the same reason we pre-warm at setup). Warm against the
    //    swapchain target explicitly in case a resize ever fires outside a swapchain
    //    context.
    internal::currentWindowContext().swapchainTarget.context = sgl_default_context();
    internal::currentWindowContext().swapchainTarget.cache.clear();
    RenderTarget* prevTarget = internal::currentWindowContext().currentTarget;
    internal::currentWindowContext().currentTarget = &internal::currentWindowContext().swapchainTarget;
    active2D(BlendMode::Alpha);
    active2D(BlendMode::Add);
    active2D(BlendMode::Multiply);
    active2D(BlendMode::Screen);
    active2D(BlendMode::Subtract);
    active2D(BlendMode::Disabled);
    activePremult();
    activeClear();
    active3D();
    internal::currentWindowContext().currentTarget = prevTarget;
    // NOTE: each FBO's RenderTarget cache (and its sgl context) is also invalidated
    // by sgl_shutdown but is NOT rebuilt here — FBOs surviving an sgl buffer resize
    // is a pre-existing limitation, out of scope for this refactor.

    sglPendingResize = 0;
}
} // namespace internal

// ---------------------------------------------------------------------------
// Clear screen (RGB float: 0.0 ~ 1.0)
// Works correctly in FBO or during swapchain pass (oF compatible)
// ---------------------------------------------------------------------------
namespace {
// Record an opaque fullscreen quad (activeClear pipeline) into the CURRENT
// sokol_gl layer — clear()'s erase semantics on the swapchain (issue #190).
// Deferred shader/PBR/point draws recorded before this stay in earlier layers
// (behind the quad); later ones composite on top. The quad is drawn at the
// far plane with depth compare ALWAYS + write enabled (pipeDescClear), so it
// also resets the depth buffer: 3D drawn after the clear() is not occluded by
// pre-clear 3D geometry. sgl just records — this works with or without an
// active render pass.
void recordSwapchainClearQuad(float r, float g, float b, float a) {
    BlendMode prevBlendMode = internal::currentWindowContext().currentBlendMode;

    sgl_push_matrix();
    sgl_matrix_mode_projection();
    sgl_push_matrix();

    internal::sglLoadProjection(internal::toBackendClip(
        Mat4::ortho(-1.0f, 1.0f, 1.0f, -1.0f, -1.0f, 1.0f)));
    sgl_matrix_mode_modelview();
    sgl_load_identity();

    internal::loadPipeline(internal::activeClear());
    sgl_disable_texture();
    sgl_begin_quads();
    sgl_c4f(r, g, b, a);
    // z = -1 maps through the GL-convention ortho above (z_ndc = -z) to the
    // far plane; toBackendClip remaps to the backend's depth range.
    sgl_v3f(-1.0f, -1.0f, -1.0f);
    sgl_v3f( 1.0f, -1.0f, -1.0f);
    sgl_v3f( 1.0f,  1.0f, -1.0f);
    sgl_v3f(-1.0f,  1.0f, -1.0f);
    sgl_end();

    sgl_matrix_mode_projection();
    sgl_pop_matrix();
    sgl_matrix_mode_modelview();
    sgl_pop_matrix();

    internal::loadPipeline(internal::active2D(prevBlendMode));
}
} // anonymous namespace

void clear(float r, float g, float b, float a /* = 1.0f */) {
    // Skip in headless mode (no graphics context)
    if (headless::isActive()) return;

    auto& ctx = internal::currentWindowContext();
    if (ctx.inFboPass && ctx.fboClearColorFunc) {
        // During FBO pass, call FBO's clearColor() to restart pass
        ctx.fboClearColorFunc(r, g, b, a);
    } else if (ctx.inSwapchainPass) {
        // During swapchain pass: erase by recording an opaque fullscreen quad
        recordSwapchainClearQuad(r, g, b, a);
    } else {
        // Outside a pass. If nothing has been recorded for the swapchain yet
        // this frame, keep the cheap path: stash the clear color as the pass
        // CLEAR action, consumed when the pass starts in ensureSwapchainPass()
        // (the normal clear()-at-top-of-draw() pattern costs nothing extra).
        // Otherwise clear() must ERASE what came before (issue #190): record
        // the opaque fullscreen quad in submission order instead.
        //
        // "Something recorded" = any sokol_gl vertices in the current
        // (swapchain) context this frame (sgl_num_vertices is per context and
        // rewinds on sg_commit), any deferred shader / PBR / point draws, or
        // a swapchain pass that already ran this frame (e.g. FullscreenShader
        // drew directly and an FBO suspended the pass — that drawable content
        // survives the resume via LOAD, see #191, so it must be erased too).
        bool hasRecorded = sgl_num_vertices() > 0
            || !ctx.deferredShaderDraws.empty()
            || !ctx.deferredPbrDraws.empty()
            || !ctx.deferredPointDraws.empty()
            || ctx.swapchainPassStartedThisFrame;
        if (hasRecorded) {
            recordSwapchainClearQuad(r, g, b, a);
        } else {
            // sgl commands accumulate without an active pass, so FBOs can
            // render in their own passes without interrupting the swapchain
            // pass; the swapchain pass itself starts in present().
            ctx.swapchainClearValue = { r, g, b, a };
        }
    }
}

// ---------------------------------------------------------------------------
// パス管理関数（non-inline: Hot Reload時にHost/Guest間で同じ状態を参照するため）
// ---------------------------------------------------------------------------
namespace {
// Start (or restart) the swapchain render pass for the current window.
// The FIRST start of a frame clears color and depth with swapchainClearValue
// (frame background). Any subsequent start — resumeSwapchainPass() after an
// FBO / shadow / reflection pass suspended it — must LOAD color AND depth so
// everything already rendered into the drawable this frame survives (issue
// #191: FullscreenShader/direct-pass content was wiped by the old
// unconditional CLEAR).
// `preserveContents` marks a pass that may be suspended and resumed later in
// the same frame (any pass started OUTSIDE present(): FullscreenShader / LUT
// force-starts, resumes after Fbo / shadow / reflection passes). Such passes
// set depth.store_action = SG_STOREACTION_STORE, which does double duty:
//   - stores the depth buffer so the resume can LOAD it (upstream sokol
//     discards swapchain depth after every pass), and
//   - on Metal + MSAA it is the hint (see the [TrussC] patch in sokol_gfx.h)
//     to store the multisample texture, which upstream resolve-only passes
//     discard — without it a resumed pass would LOAD undefined content.
// The final pass started in present() passes false, so the normal
// clear-at-top-of-draw() frame keeps today's exact store behavior (resolve-
// only color, discarded depth) — zero bandwidth regression.
void beginSwapchainPassInternal(bool preserveContents) {
    auto& ctx = internal::currentWindowContext();
    sg_pass pass = {};
    if (!ctx.swapchainPassStartedThisFrame) {
        pass.action.colors[0].load_action = SG_LOADACTION_CLEAR;
        pass.action.colors[0].clear_value = ctx.swapchainClearValue;
        pass.action.depth.load_action = SG_LOADACTION_CLEAR;
        pass.action.depth.clear_value = 1.0f;
    } else {
        pass.action.colors[0].load_action = SG_LOADACTION_LOAD;
        pass.action.depth.load_action = SG_LOADACTION_LOAD;
    }
    if (preserveContents) {
        pass.action.depth.store_action = SG_STOREACTION_STORE;
    }
    // Secondary windows provide their own swapchain (same drawable for the
    // whole window frame); the main window uses sokol_glue as before.
    pass.swapchain = ctx.acquireSwapchain ? ctx.acquireSwapchain(ctx.acquireSwapchainUser)
                                          : sglue_swapchain();
    // Record the drawable we render into so end-of-frame capture reads back
    // THIS one (sapp_get_swapchain() advances the Metal drawable per call).
    ctx.lastSwapchainDrawable = pass.swapchain.metal.current_drawable;
    // Record the whole swapchain too: the Windows / Linux capture backends read
    // this window's render_view / gl.framebuffer + size from here (mac uses the
    // drawable above). Main window: this is sglue_swapchain(), i.e. identical to
    // sapp_get_swapchain(), so the main capture path is unchanged.
    ctx.lastSwapchain = pass.swapchain;
    sg_begin_pass(&pass);
    ctx.inSwapchainPass = true;
    ctx.swapchainPassStartedThisFrame = true;
}
} // anonymous namespace

void ensureSwapchainPass() {
    if (!internal::currentWindowContext().inSwapchainPass && !internal::currentWindowContext().inFboPass) {
        // Callers outside present() (FullscreenShader, tcxLut, ...) force-start
        // the pass mid-frame; it may be suspended by an Fbo/shadow pass later,
        // so its contents must be preserved.
        beginSwapchainPassInternal(true);
    }
}

void present() {
    if (headless::isActive()) return;

    // Final pass of the frame — nothing suspends it, so no preserve hint
    // (keeps the normal one-pass frame's store behavior unchanged).
    if (!internal::currentWindowContext().inSwapchainPass && !internal::currentWindowContext().inFboPass) {
        beginSwapchainPassInternal(false);
    }

    internal::flushDeferredShaderDraws();

    events().onRender.notify();

    sgl_error_t err = sgl_error();
    if (err.vertices_full || err.commands_full) {
        int newVerts = internal::sglMaxVertices * 4;
        if (newVerts > internal::sglPendingResize) {
            internal::sglPendingResize = newVerts;
            logNotice("sokol_gl") << "Vertex buffer overflow detected ("
                << internal::sglMaxVertices << " vertices, "
                << internal::sglMaxCommands << " commands). "
                << "Will resize to " << newVerts << " next frame.";
        }
    }

    sg_end_pass();
    internal::currentWindowContext().inSwapchainPass = false;
    // Frame is over: the next swapchain pass start belongs to the next frame
    // and must CLEAR again with swapchainClearValue (see issue #191).
    internal::currentWindowContext().swapchainPassStartedThisFrame = false;
    sg_commit();

    // Now that every deferred draw (swapchain layers above, FBO passes at
    // their Fbo::end()) has been submitted, it is safe to destroy the GPU
    // resources released during this frame (temporary Mesh draws, texture
    // re-uploads, atlas growth, sampler changes, ...).
    internal::drainPendingGpuDestroys();
}

bool isInSwapchainPass() {
    return internal::currentWindowContext().inSwapchainPass;
}

void suspendSwapchainPass() {
    if (internal::currentWindowContext().inSwapchainPass) {
        sg_end_pass();
        internal::currentWindowContext().inSwapchainPass = false;
    }
}

void resumeSwapchainPass() {
    if (!internal::currentWindowContext().inSwapchainPass) {
        // Restart uses LOAD when the pass already ran this frame — see
        // beginSwapchainPassInternal() (issue #191). A resumed pass may be
        // suspended again (multiple Fbo blocks), so preserve its contents too.
        beginSwapchainPassInternal(true);
    }
}

// ---------------------------------------------------------------------------
// Non-inline singletons / accessors (Hot Reload: Host/Guest share state)
// ---------------------------------------------------------------------------

namespace internal {
// The main window's state container. Non-inline so a hot-reload guest binds
// to the host's instance (same pattern as events()/getDefaultContext()).
WindowContext& mainWindowContext() {
    static WindowContext ctx;
    return ctx;
}

// Open-window registry (see tcWindow.h). Non-inline for the same host/guest
// reason as mainWindowContext(). Main thread only.
static std::vector<Window*>& windowRegistryStorage() {
    static std::vector<Window*> list;
    return list;
}
void registerWindow(Window* w) {
    windowRegistryStorage().push_back(w);
}
void unregisterWindow(Window* w) {
    auto& list = windowRegistryStorage();
    list.erase(std::remove(list.begin(), list.end(), w), list.end());
}
std::vector<Window*> openWindows() {
    std::vector<Window*> out;
    for (Window* w : windowRegistryStorage()) {
        if (w && w->isOpen()) out.push_back(w);
    }
    return out;
}

// Unregister a destroyed Light from every window context's activeLights, so a
// still-registered Light never dangles (the PBR pipeline derefs those pointers
// every lit draw — issue: ~Light() had no cleanup). Called by ~Light()
// (declared in tcLight.h); defined here because it needs the Window registry.
// Non-inline keeps it host/guest-shared under hot reload, same as the registry.
void removeLightFromAllContexts(Light* light) {
    auto scrub = [&](WindowContext& ctx) {
        auto& v = ctx.activeLights;
        v.erase(std::remove(v.begin(), v.end(), light), v.end());
    };
    scrub(mainWindowContext());
    for (Window* w : openWindows()) {
        if (w) scrub(w->context());
    }
}
} // namespace internal

CoreEvents& events() {
    // The CoreEvents instance is owned per window context. The main window's
    // is wired lazily here (preserving the pre-context construction timing);
    // Phase 1 pre-wires the pointer when constructing secondary contexts.
    auto& ctx = internal::currentWindowContext();
    if (!ctx.coreEvents) {
        static CoreEvents instance;   // main-window storage
        ctx.coreEvents = &instance;
    }
    return *ctx.coreEvents;
}

double getElapsedTime() {
    auto now = std::chrono::high_resolution_clock::now();
    if (!internal::startTimeInitialized) {
        internal::startTime = now;
        internal::startTimeInitialized = true;
        return 0.0;
    }
    auto duration = std::chrono::duration<double>(now - internal::startTime);
    return duration.count();
}

// getFrameCount()/getUpdateCount() resolve through the CURRENT window context.
// The main window keeps returning internal::updateFrameCount — bit-identical to
// the old global, and the value the hot-reload host mirrors (tcHotReloadHost.h)
// — while a secondary window returns its own per-tick counter (advanced in the
// native windowTick before update()). Single-window apps are unaffected.
uint64_t getUpdateCount() {
    auto& ctx = internal::currentWindowContext();
    return ctx.isMain ? internal::updateFrameCount : ctx.updateCount;
}

// Device/main-window frame count. Left on sapp_frame_count(): it is the
// sokol_app frame index used for one-update-per-device-frame guards, not a
// per-window update counter (secondary draws happen within main-thread ticks
// and are not tracked separately).
uint64_t getDrawCount() {
    return sapp_frame_count();
}

uint64_t getFrameCount() {
    auto& ctx = internal::currentWindowContext();
    return ctx.isMain ? internal::updateFrameCount : ctx.updateCount;
}

double getDeltaTime() {
    // Per-window: inside a secondary window's update/draw this is that
    // window's own tick delta, not the main window's.
    return internal::currentWindowContext().updateDeltaTime;
}

double getFrameRate() {
    auto& ctx = internal::currentWindowContext();
    double dt = ctx.updateDeltaTime;
    if (dt <= 0.0) return 0.0;
    ctx.frameTimeBuffer[ctx.frameTimeIndex] = dt;
    ctx.frameTimeIndex = (ctx.frameTimeIndex + 1) % 10;
    if (ctx.frameTimeIndex == 0) {
        ctx.frameTimeBufferFilled = true;
    }

    int count = ctx.frameTimeBufferFilled ? 10 : ctx.frameTimeIndex;
    if (count == 0) return 0.0;

    double sum = 0.0;
    for (int i = 0; i < count; i++) {
        sum += ctx.frameTimeBuffer[i];
    }
    double avgDt = sum / count;
    return avgDt > 0.0 ? 1.0 / avgDt : 0.0;
}

namespace internal {
ElapsedTimeClock& getElapsedClock() {
    static ElapsedTimeClock clock;
    return clock;
}
} // namespace internal

Logger& getLogger() {
    static Logger logger;
    return logger;
}

} // namespace trussc
